"""
Assemble full HTML and write PDF via WeasyPrint.
"""
from pathlib import Path

from tools.pdf_report.tokens import esc
from tools.pdf_report.styles import get_css
from tools.pdf_report import sections


def build_full_html(
    project_id: str,
    title: str,
    date: str,
    body_html: str,
    references_html: str,
    cover_html: str,
    outcome_html: str,
    claim_map_html: str,
    trajectory_html: str,
    evidence_html: str,
    disagreement_html: str,
    insight_html: str,
    action_html: str,
) -> str:
    """Build the complete HTML document for the report."""
    css = get_css()
    return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>Intelligence Artifact – {esc(project_id)}</title>
<style>{css}</style></head>
<body>

{cover_html}

<!-- 1. OUTCOME LAYER -->
{sections.section_header(1, "Outcome Layer")}
{outcome_html}

<!-- 2. CLAIM STATE MAP -->
{sections.section_header(2, "Claim State Map")}
{claim_map_html}

<!-- 3. BELIEF TRAJECTORY -->
{sections.section_header(3, "Belief Trajectory")}
{trajectory_html}

<!-- 4. EVIDENCE LANDSCAPE -->
{sections.section_header(4, "Evidence Landscape")}
{evidence_html}

<!-- 5. DISAGREEMENT LAYER -->
{sections.section_header(5, "Disagreement Layer")}
{disagreement_html}

<!-- 6. INSIGHT LAYER -->
{sections.section_header(6, "Insight Layer")}
{insight_html}

<!-- 7. ACTION LAYER -->
{sections.section_header(7, "Action Layer")}
{action_html}

<!-- AUDITOR MODE -->
<div class="auditor-div">
  <h2>Full Report — Auditor Mode</h2>
  <p>Complete narrative with source attributions</p>
</div>
<div class="report-body">{body_html}</div>

<!-- REFERENCES -->
{sections.section_header(8, "References")}
<div class="references">{references_html}</div>

<div class="disclaimer">
  <strong>Disclaimer:</strong> This intelligence artifact was generated by an automated epistemic research system (AEM).
  Claim states reflect algorithmic assessment of evidence quality. All findings should be independently validated.
  Generated {date}.
</div>

</body></html>"""


def write_pdf(html: str, pdf_path: Path, base_url: str) -> None:
    """Render HTML to PDF with WeasyPrint."""
    from weasyprint import HTML as WP_HTML
    WP_HTML(string=html, base_url=base_url).write_pdf(pdf_path)
